---
output:
  github_document
---

```{r}
library(tidyverse)
library(repurrrsive)
```


```{r}
x <- list(a = c(1, 4, 7),
          b = c(1, 2, 3, 4, 5, 6, 7),
          c = c(10, 20, 30, 70, 90),
          d = c(13, 56, 23, 75))

x
```

```{r}
means <- numeric(length(x))
for(ii in seq_along(x)){
  means[ii] <- mean(x[[ii]])
}

means

setNames(means, names(x))
```

```{r}
# map(.x, .f)
map(x, mean)

map_dbl(x, mean)
map_df(x, mean)
```


```{r}
got_chars

got_chars[[1]]

map_chr(got_chars, "name")

map_chr(got_chars, "born")

map_chr(got_chars, ~glue::glue("{.x$name} was born {.x$born}"))
```


```{r}
x <- c(1, 4, 6, 8)
y <- c(1, 2, 3, 4)

map2(x, y, rep)
```

```{r}
excelfile <- here("data", "ians_example_20180225.xlsx")

excelsheets <- readxl::excel_sheets(excelfile)

readsheet <- function(file, sheet){
  readxl::read_excel(file, sheet) %>% 
    mutate(sheet = sheet,
           file = fs::path_file(file))
}

readsheet(excelfile, "day_1")

mydata <- map_df(excelsheets, ~readsheet(excelfile, .x))

```



```{r}
mpg

map(mpg, mean)

purrr::modify_if(mpg, is_character, str_to_upper) %>% as_tibble

keep(mpg, is_bare_numeric) %>% map_df(mean)


mpg %>% 
  mutate_if(is_bare_numeric, ~round(.) %>% as.integer())
```



